title: "Muxing Wang"
author: "Muxing Wang"
description: "NEU"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false          # standard centered layout with header nav
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "/#publications", title: "Publications"}
  - {url: "/#education", title: "Education"}

external: false

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
